### ISSUE TITLE
MODELSDICT_default is empty and hard-coded paths

### ISSUE THREAD

**Issue by ttshimiz** [GabrielaCR/AGNfitter#1]
Hi Gabriela! 
I saw your paper on arxiv today and wanted to try it out on my sample of low-redshift AGN. AGNfitter looks awesome but I wanted to let you know a couple of issues I've run into while trying it out.

1.) The MODELSDICT_default file you provided is empty which is fine because I figured out if I just deleted it the code would create a new one. However...

2.) When trying to create a new model dictionary, it looks like when the pickle files are being loaded, the code is importing 'CONSTRUCT_modelobjects' which then causes it to run lines 109-126. This would be fine however you have some hard-coded paths within this function in lines 60 and 105. I changed those but then also realized you didn't provide 'DALE.list', 'CHARY_ELBAZ.list', 'torus_templates_list.dat', or 'richardsbbb.dat'. So in the end I ended up just commenting out lines 109-126.

After those small issues, everything worked great in the test run!

**Comment by GabrielaCR** [comment]
Dear Taro,

thank you very much! I will update the code with the corrected version.
I'm glad that it worked at the end.
This is exactly the kind of issue I would like to correct till the end of the month from this beta version.
Thanks again!

**Comment by GabrielaCR** [comment]
Dear Taro,
this issue was solved, _please download the new corrected version_.

By commenting those lines, it may solve it for the example model library, but not for future model library constructions. The real problem was that the object from the model classes still had dependencies on some other files which were not included in the package. Now they are completely independent.

Thanks,
Gabriela
