### ISSUE TITLE
building a large dictionary -- memory limitation?

### ISSUE THREAD

**Issue by lmorabit** [GabrielaCR/AGNfitter#12]
When building the dictionary, is there a way to gracefully limit the memory?  When running AGNfitter on a cluster, the program is exceeding the memory limits when it gets through about 22 per cent of building the dictionary.  It would be extremely useful to be able to cap the amount of memory used.

**Comment by wndywllms** [comment]
The size of the models dictionary stored in memory will depend on the number of sources in the catalogue (or the specified z array in the SETTINGS) and there is no way to reduce this... you can either subdivide the catalogue or what I typically do for large catalogues is run in the independent mode (-i flag and specify a source number, so that the dictionary is only created for the redshift of the source being processed) and use an array job on the cluster to run all sources in the catalogue (see AGNfitter/example/run_agnfitter.qsub)
