### ISSUE TITLE
Operands could not be broadcast together with shapes (10,18) (12,)

### ISSUE THREAD

**Issue by eilatg** [GabrielaCR/AGNfitter#14]
We are using your AGNFitter code to study the SEDs of red quasars from Glikman et al. (2012) as it is the only one that mixes galaxies and AGN with dust reddening. 

Using our defined photometry file (following the syntax in the example), the code executes, goes through various burn in iterations, but as the code finishes running, we get the following error: 

Traceback (most recent call last):
  File "/astro/linux/64/agnfitter/current/RUN_AGNfitter_multi.py", line 262, in <module>
    RUN_AGNfitter_multiprocessing(args.ncpu, data_ALL, Modelsdict)
  File "/astro/linux/64/agnfitter/current/RUN_AGNfitter_multi.py", line 201, in RUN_AGNfitter_multiprocessing
    catalog_fitting = pool.map(multi_run_wrapper, itertools.izip(range(nsources), itertools.repeat(data_obj), itertools.repeat(modelsdict)))
  File "/astro/linux/64/anaconda/python2/current/lib/python2.7/multiprocessing/pool.py", line 251, in map return self.map_async(func, iterable, chunksize).get()
  File "/astro/linux/64/anaconda/python2/current/lib/python2.7/multiprocessing/pool.py", line 558, in get raise self._value
ValueError: operands could not be broadcast together with shapes (10,18) (12,) 

The code does produce output directories for our two sources, but they lack PDF plots. 

We tried the suggestions in thread #6 (i.e., overwriting the model libraries with '--overwrite' and we deleted the MODELSDICT_default file manually as well).  Neither solved the problem.

Help!!

**Comment by GabrielaCR** [comment]
Dear Eilat,
the inconsistent shapes "(10,18) (12,)" hint towards a bug in the choice of the filters, meaning that they (18) are not consistent to the data (12). 18 is the SED length in the example case, so or the dictionary is not being updated to your personalised filters (but --overwrite should do this automatically, so this may not be the case.), or you are not choosing the correct number of filters in the setting files. So please try to check that the filters that are chosen in the settings_file are 12, such as the data points. If you don't find any issue please send me the settings file by email so that I can check it. I hope this helped!

**Comment by eilatg** [comment]
Thank you! We didn't realize that the output filters needed to match the input filters (I now see that it is explained in the wiki!).  The code now works! Thank you for the help.
