### ISSUE TITLE
Model is created with 18 bands even if the user specifies other filter sets

### ISSUE THREAD

**Issue by GabrielaCR** [GabrielaCR/AGNfitter#6]
> emcee:
> Exception while calling your likelihood function:
  exception:
>...
>IndexError: index 18 is out of bounds for axis 0 with size 18
>

**Comment by GabrielaCR** [comment]
Every time the user constructs a new model library it does not overwrite automatically. There are two options to create the new library: 1. You need to specify this as a command '--overwrite' (see https://github.com/GabrielaCR/AGNfitter/wiki/Runtime-options) or 2. you can manually erase the dictionary AGNfitter/models/MODELSDICT_default. 

The reason for not overwriting automatically is that the model library construction is relatively time expensive, for which ideally you should construct the dictionary you need only once and run the fitting code independently.

**Comment by kk9194** [comment]
I was having this issue, every catalog I tried to use had Model set contains 18 bands, this helped resolve that issue. However, I am a little confused. I have two catalogs that I will be using. They have some overlapping sources and some completely different sources. So do I need to use the --overwrite command every time I run AGNfitter for a new catalog? Or is it just needed the first time to remove MODELSDICT_default?

Also, since these two catalogs have some of the same sources, will the OUTPUT folder contain multiple directories for one source since that source appeared in both catalogs? Or will AGNfitter recognize that one of the sources in my second catalog was already completed in the first catalog and does not need a new folder in OUTPUT?
